import 'package:project/provider/shop_provider.dart';

final List<Bahan> semuaBahanList = [
  Bahan(
    nama: 'Tomat',
    harga: 3000,
    tersedia: true,
    gambar: 'img-project/tomat.jpg',
    satuan: 'per kg',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Sup oyong telur puyuh',
    harga: 15000,
    tersedia: true,
    gambar:
        'img-project/sup-oyong-telur-puyuh-untuk-sarapan-ini-resepnya-05oNyycUoC.jpg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'Bayam',
    harga: 2000,
    tersedia: false,
    gambar: 'img-project/bayam.jpg',
    satuan: 'per ikat',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Sate tempe bakar',
    harga: 2000,
    tersedia: true,
    gambar: 'img-project/sate tempe bakar.jpg',
    satuan: 'per tusuk',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'Wortel',
    harga: 4000,
    tersedia: true,
    gambar: 'img-project/wortel.jpg',
    satuan: 'per kg',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Brokoli',
    harga: 6000,
    tersedia: true,
    gambar: 'img-project/brokoli.jpeg',
    satuan: 'per kg',
    kategori: 'Bahan Makanan',
  ),

  Bahan(
    nama: 'Ayam',
    harga: 15000,
    tersedia: false,
    gambar: 'img-project/Ayam.jpg',
    satuan: 'per ekor',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Gado-Gado',
    harga: 12000,
    tersedia: true,
    gambar: 'img-project/gado gado.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'Kolak Pisang',
    harga: 18000,
    tersedia: false,
    gambar: 'img-project/kolak pisang.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'ikan kuah kuning',
    harga: 10000,
    tersedia: true,
    gambar: 'img-project/ikan kuah kuning.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'telur',
    harga: 2000,
    tersedia: true,
    gambar: 'img-project/telur.jpeg',
    satuan: 'per buah',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Minyak kelapa murni/vco',
    harga: 8000,
    tersedia: true,
    gambar: 'img-project/vco.jpeg',
    satuan: 'per botol',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Salad Buah',
    harga: 12000,
    tersedia: true,
    gambar: 'img-project/salad_buah.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'Kacang Almond',
    harga: 17000,
    tersedia: true,
    gambar: 'img-project/kacang_almond.jpeg',
    satuan: 'per bungkus',
    kategori: 'Bahan Makanan',
  ),
  Bahan(
    nama: 'Vegan burger',
    harga: 15000,
    tersedia: false,
    gambar: 'img-project/vegan_burger.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
  Bahan(
    nama: 'Bento Sehat',
    harga: 18000,
    tersedia: true,
    gambar: 'img-project/bento_sehat.jpeg',
    satuan: 'per porsi',
    kategori: 'Makanan Sehat',
  ),
];
